# Generated by Django 5.2.6 on 2026-08-31 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidancePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('guidance_key', models.SlugField(help_text='The identifier the triage rules use to find this page. Changing it will break the route that points here.', max_length=100, unique=True)),
                ('summary', models.TextField(help_text='A short plain-English description of the possible next step. Signpost only: describe what a person could do and who can help, and do not give legal advice.', max_length=600)),
                ('lease_url', models.URLField(help_text='The page on lease-advice.org holding the authoritative guidance. The prototype links out to it rather than copying its wording.', verbose_name='LEASE guidance URL')),
            ],
            options={
                'verbose_name': 'guidance page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
